import { Github, Mail, Linkedin } from "lucide-react";

/* ============================================================
   PLACEHOLDERS: reemplaza los valores marcados con tus datos.
   ============================================================ */

export const personalData = {
    name: "Hernán Ludeña",
    firstName: "Hernán",
    lastName: "Ludeña",
    shortName: "Hernán",
    logoSuffix: "Ludeña",
    role: "Tech Lead",
    email: "hernanludena@yahoo.com",
    phone: "+593 99 109 2704",
    location: "Loja, Ecuador",
    linkedin: "https://ec.linkedin.com/in/hernanludena",
    resumeUrl: "/CV-Hernan-Ludena.pdf",
};

export const socialNetworks = [
    {
        id: 1,
        logo: <Github size={24} strokeWidth={1} />,
        src: "https://github.com/hludena",
    },
    {
        id: 2,
        logo: <Linkedin size={24} strokeWidth={1} />,
        src: "https://ec.linkedin.com/in/hernanludena",
    },
];

// Navegación superior estilo Bryan actual (enlaces de texto)
export const itemsNavbar = [
    { id: 1, key: "nav.home", link: "/" },
    { id: 2, key: "nav.about", link: "/about" },
    { id: 3, key: "nav.experience", link: "/experience" },
    { id: 4, key: "nav.skills", link: "/skills" },
    { id: 5, key: "nav.projects", link: "/projects" },
    { id: 6, key: "nav.blog", link: "/blog" },
    { id: 8, key: "nav.hackerrank", link: "/hackerrank" },
    { id: 9, key: "nav.contact", link: "/contact" },
] as const;

// Bloque de stats (About) — reusa react-countup
export const dataCounter = [
    {
        id: 0,
        endCounter: 19,
        textKey: "counter.years",
        lineRight: true,
        lineRightMobile: true,
    },
    {
        id: 1,
        endCounter: 7,
        textKey: "counter.companies",
        lineRight: true,
        lineRightMobile: false,
    },
    {
        id: 2,
        endCounter: 33,
        textKey: "counter.certs",
        lineRight: false,
        lineRightMobile: false,
    },
] as const;

const di = (path: string) =>
    `https://raw.githubusercontent.com/devicons/devicon/master/icons/${path}.svg`;
const si = (slug: string) => `https://cdn.simpleicons.org/${slug}`;
const gb = (name: string) =>
    `https://cdn.jsdelivr.net/gh/gilbarbara/logos/logos/${name}.svg`;
const vz = (path: string) => `https://www.vectorlogo.zone/logos/${path}.svg`;
/** Text badge when no brand logo exists */
const badge = (label: string, bg: string) => {
    const fontSize = label.length > 6 ? 10 : label.length > 4 ? 13 : 18;
    const svg = `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 64 64"><rect width="64" height="64" rx="10" fill="${bg}"/><text x="32" y="40" text-anchor="middle" font-family="Arial,sans-serif" font-size="${fontSize}" font-weight="700" fill="#fff">${label}</text></svg>`;
    return `data:image/svg+xml,${encodeURIComponent(svg)}`;
};

// Sección "Con qué trabajo" — skills por categorías con iconos (estilo tech stack)
export const skillsData = [
    {
        id: 1,
        categoryKey: "skills.cat.backend",
        items: [
            { name: "Java", icon: di("java/java-original") },
            { name: "Spring", icon: di("spring/spring-original") },
            { name: "Spring Boot", icon: di("spring/spring-original") },
            { name: "Spring Cloud", icon: si("spring") },
            { name: "Struts", icon: vz("apache_struts/apache_struts-icon") },
            { name: "Hibernate / JPA", icon: si("hibernate") },
            { name: "MyBatis", icon: badge("MyBatis", "#E06C00") },
            { name: "MapStruct", icon: badge("MapS", "#0254D2") },
            { name: "SOAP", icon: badge("SOAP", "#1B4F72") },
            { name: "REST", icon: si("swagger") },
            { name: "OpenFeign", icon: badge("Feign", "#6DB33F") },
            { name: "gRPC", icon: di("grpc/grpc-original") },
            { name: "Resilience4j", icon: badge("R4j", "#3D8B37") },
            { name: "Go", icon: di("go/go-original-wordmark") },
            { name: "Node.js", icon: di("nodejs/nodejs-original") },
            { name: ".NET / C#", icon: di("dotnetcore/dotnetcore-original") },
        ],
    },
    {
        id: 2,
        categoryKey: "skills.cat.platforms",
        items: [
            { name: "Tomcat", icon: di("tomcat/tomcat-original") },
            { name: "JBoss", icon: gb("wildfly") },
            { name: "Firebase", icon: di("firebase/firebase-plain") },
            { name: "Salesforce", icon: di("salesforce/salesforce-original") },
            { name: "OutSystems", icon: badge("OutSys", "#CF0072") },
        ],
    },
    {
        id: 3,
        categoryKey: "skills.cat.architecture",
        items: [
            { name: "Microservices", icon: badge("µSvc", "#2563EB") },
            { name: "Hexagonal Architecture", icon: badge("Hex", "#7C3AED") },
            { name: "Clean Architecture", icon: badge("Clean", "#0F766E") },
            { name: "DDD", icon: badge("DDD", "#B45309") },
            { name: "CQRS", icon: badge("CQRS", "#BE185D") },
            { name: "Event Driven Architecture", icon: badge("EDA", "#0369A1") },
            { name: "Saga Pattern", icon: badge("Saga", "#9333EA") },
            { name: "API Gateway", icon: badge("APIGW", "#334155") },
            { name: "Service Discovery", icon: badge("Disc", "#0891B2") },
            { name: "Circuit Breaker", icon: badge("CB", "#DC2626") },
            { name: "OpenAPI / Swagger", icon: si("swagger") },
            { name: "Async APIs", icon: badge("Async", "#4F46E5") },
            { name: "SOLID", icon: badge("SOLID", "#1D4ED8") },
            { name: "System Design", icon: badge("SysD", "#475569") },
        ],
    },
    {
        id: 4,
        categoryKey: "skills.cat.security",
        items: [
            { name: "OAuth2", icon: gb("oauth") },
            { name: "OpenID Connect", icon: si("openid/F78C40") },
            { name: "JWT", icon: si("jsonwebtokens") },
            { name: "Keycloak", icon: si("keycloak") },
            { name: "Spring Security", icon: si("springsecurity/6DB33F") },
            { name: "SSL/TLS", icon: si("openssl/721412") },
            { name: "OWASP Top 10", icon: si("owasp/99CC33") },
        ],
    },
    {
        id: 5,
        categoryKey: "skills.cat.messaging",
        items: [
            { name: "Kafka", icon: si("apachekafka/FFFFFF") },
            { name: "RabbitMQ", icon: di("rabbitmq/rabbitmq-original") },
            { name: "ActiveMQ", icon: vz("apache_activemq/apache_activemq-icon") },
        ],
    },
    {
        id: 6,
        categoryKey: "skills.cat.observability",
        items: [
            { name: "DataDog", icon: si("datadog") },
            { name: "New Relic", icon: si("newrelic") },
            { name: "Prometheus", icon: di("prometheus/prometheus-original") },
            { name: "Kibana", icon: di("kibana/kibana-original") },
        ],
    },
    {
        id: 7,
        categoryKey: "skills.cat.aws",
        items: [
            { name: "EC2", icon: gb("aws-ec2") },
            { name: "ECS", icon: gb("aws-ecs") },
            { name: "Lambda", icon: gb("aws-lambda") },
            { name: "API Gateway", icon: gb("aws-api-gateway") },
            { name: "Cognito", icon: gb("aws-cognito") },
            { name: "CloudWatch", icon: gb("aws-cloudwatch") },
            { name: "S3", icon: gb("aws-s3") },
            { name: "RDS", icon: gb("aws-rds") },
            { name: "SQS", icon: gb("aws-sqs") },
            { name: "Secrets Manager", icon: gb("aws-secrets-manager") },
            { name: "IAM", icon: gb("aws-iam") },
        ],
    },
    {
        id: 8,
        categoryKey: "skills.cat.azure",
        items: [
            { name: "App Service", icon: di("azure/azure-original") },
            { name: "Azure Functions", icon: gb("microsoft-azure") },
        ],
    },
    {
        id: 9,
        categoryKey: "skills.cat.devops",
        items: [
            { name: "Docker", icon: di("docker/docker-original") },
            { name: "Kubernetes", icon: di("kubernetes/kubernetes-original") },
            { name: "Git", icon: di("git/git-original") },
            { name: "GitHub Actions", icon: di("githubactions/githubactions-original") },
            { name: "Bitbucket Pipelines", icon: di("bitbucket/bitbucket-original") },
            { name: "Jenkins", icon: di("jenkins/jenkins-original") },
            { name: "Helm", icon: di("helm/helm-original") },
            { name: "ArgoCD", icon: si("argo") },
            { name: "Nginx", icon: di("nginx/nginx-original") },
            { name: "HAProxy", icon: si("haproxy") },
            { name: "Cloudflare", icon: di("cloudflare/cloudflare-original") },
        ],
    },
    {
        id: 10,
        categoryKey: "skills.cat.frontend",
        items: [
            { name: "React", icon: di("react/react-original") },
            { name: "Next.js", icon: di("nextjs/nextjs-original") },
            { name: "Vite", icon: di("vitejs/vitejs-original") },
            { name: "React Router", icon: si("reactrouter") },
            { name: "Redux Toolkit", icon: di("redux/redux-original") },
            { name: "Tailwind CSS", icon: di("tailwindcss/tailwindcss-original") },
            { name: "Axios", icon: si("axios") },
            { name: "TypeScript", icon: di("typescript/typescript-original") },
            { name: "JavaScript", icon: di("javascript/javascript-original") },
            { name: "AngularJS", icon: di("angularjs/angularjs-original") },
            { name: "JSP", icon: badge("JSP", "#ED8B00") },
            { name: "JSF", icon: badge("JSF", "#0076A3") },
            { name: "Apache Cordova", icon: si("apachecordova/FFFFFF") },
            { name: "HTML5", icon: di("html5/html5-original") },
            { name: "CSS3", icon: di("css3/css3-original") },
        ],
    },
    {
        id: 11,
        categoryKey: "skills.cat.testing",
        items: [
            { name: "JUnit 5", icon: si("junit5") },
            { name: "Mockito", icon: "https://avatars.githubusercontent.com/u/975424?s=128" },
            { name: "Playwright", icon: si("playwright") },
            { name: "Selenium", icon: di("selenium/selenium-original") },
            { name: "Jest", icon: di("jest/jest-plain") },
            { name: "React Testing Library", icon: si("testinglibrary") },
        ],
    },
    {
        id: 12,
        categoryKey: "skills.cat.databases",
        items: [
            { name: "Oracle", icon: di("oracle/oracle-original") },
            { name: "SQL Server", icon: di("microsoftsqlserver/microsoftsqlserver-plain") },
            { name: "PostgreSQL", icon: di("postgresql/postgresql-original") },
            { name: "MySQL", icon: di("mysql/mysql-original") },
            { name: "Redis", icon: di("redis/redis-original") },
            { name: "MongoDB", icon: di("mongodb/mongodb-original") },
            { name: "Elasticsearch", icon: di("elasticsearch/elasticsearch-original") },
            { name: "SQL / PL-SQL", icon: badge("PL/SQL", "#F80000") },
        ],
    },
    {
        id: 13,
        categoryKey: "skills.cat.python",
        items: [
            { name: "Python", icon: di("python/python-original") },
            { name: "FastAPI", icon: di("fastapi/fastapi-original") },
            { name: "SQLAlchemy", icon: si("sqlalchemy") },
            { name: "Pydantic", icon: si("pydantic") },
        ],
    },
    {
        id: 14,
        categoryKey: "skills.cat.ai",
        items: [
            { name: "Claude Code", icon: si("claude") },
            { name: "Cursor", icon: si("cursor/FFFFFF") },
            { name: "Windsurf", icon: si("windsurf") },
            { name: "OpenCode", icon: si("opencode/FFFFFF") },
            { name: "MCP", icon: si("modelcontextprotocol") },
            {
                name: "AI Agents",
                icon: "data:image/svg+xml,%3Csvg xmlns='http://www.w3.org/2000/svg' viewBox='0 0 24 24' fill='%2360a5fa'%3E%3Cpath d='M12 2a2 2 0 0 1 2 2v1h2a3 3 0 0 1 3 3v2h1a2 2 0 1 1 0 4h-1v2a3 3 0 0 1-3 3h-2v1a2 2 0 1 1-4 0v-1H8a3 3 0 0 1-3-3v-2H4a2 2 0 1 1 0-4h1V8a3 3 0 0 1 3-3h2V4a2 2 0 0 1 2-2zm-3 8a1.5 1.5 0 1 0 0 3 1.5 1.5 0 0 0 0-3zm6 0a1.5 1.5 0 1 0 0 3 1.5 1.5 0 0 0 0-3z'/%3E%3C/svg%3E",
            },
            { name: "Spring AI", icon: di("spring/spring-original") },
            { name: "n8n", icon: si("n8n") },
        ],
    },
    {
        id: 15,
        categoryKey: "skills.cat.tools",
        items: [
            { name: "IntelliJ IDEA", icon: di("intellij/intellij-original") },
            { name: "VS Code", icon: di("vscode/vscode-original") },
            { name: "Postman", icon: di("postman/postman-original") },
            { name: "JIRA", icon: di("jira/jira-original") },
            { name: "Confluence", icon: si("confluence/2684FF") },
            { name: "SonarQube", icon: di("sonarqube/sonarqube-original") },
            { name: "Nexus", icon: si("sonatype") },
            { name: "Artifactory", icon: si("jfrog") },
            { name: "OpenAPI / Swagger", icon: si("swagger") },
            { name: "Maven", icon: di("maven/maven-original") },
            { name: "Bitbucket", icon: di("bitbucket/bitbucket-original") },
            { name: "Android Studio", icon: di("androidstudio/androidstudio-original") },
            { name: "Figma", icon: di("figma/figma-original") },
            { name: "Scrum Master", icon: si("scrumalliance") },
            { name: "Kanban / SAFe", icon: badge("SAFe", "#0052CC") },
        ],
    },
];

// Timeline de experiencia (About) — datos reales LinkedIn / CV
export const dataAboutPage = [
    {
        id: 1,
        title: "Full Stack Developer",
        company: "SoFi Tech Solutions",
        location: "Loja, Ecuador",
        period: "Feb 2024 - Actualidad",
        workMode: "Remoto",
        logo: "/experience-logos/sofi-logo-dev.png",
        logoAlt: "SoFi Tech Solutions logo",
        logoVariant: "icon",
        logoFit: "cover",
        summary:
            "Diseño, desarrollo y mantenimiento de APIs Java y interfaces React para soluciones de core bancario en un entorno financiero de alta exigencia.",
        periodEn: "Feb 2024 - Present",
        workModeEn: "Remote",
        highlights: [
            "Construcción y evolución de servicios backend Java con foco en estabilidad, rendimiento y mantenibilidad.",
            "Desarrollo full stack con React.js, integrando frontend y APIs en flujos de negocio bancarios.",
            "Aplicación de principios SOLID, patrones de diseño y code reviews sobre componentes críticos.",
            "Resolución de incidencias en entornos de alta disponibilidad con impacto directo en operación.",
        ],
        summaryEn:
            "Design, development and maintenance of Java APIs and React interfaces for core banking solutions in a high-demand financial environment.",
        highlightsEn: [
            "Built and evolved Java backend services focused on stability, performance and maintainability.",
            "Delivered full-stack work with React.js, integrating frontend and APIs in banking business flows.",
            "Applied SOLID principles, design patterns and code reviews on critical components.",
            "Resolved incidents in high-availability environments with direct operational impact.",
        ],
        tech: ["Java", "React.js", "Spring", "Oracle", "Docker"],
    },
    {
        id: 2,
        title: "Coordinador de Desarrollo y Desarrollador Full Stack Java",
        company: "iuvity",
        location: "Loja, Ecuador",
        period: "Oct 2021 - May 2024",
        workMode: "Remoto",
        logo: "/experience-logos/iuvity-icon.png",
        logoAlt: "iuvity logo",
        logoVariant: "icon",
        logoFit: "contain",
        summary:
            "Líder técnico a cargo de un equipo de desarrollo y responsable de las definiciones técnicas de proyectos de banca digital web y móvil.",
        titleEn: "Development Coordinator & Full Stack Java Developer",
        periodEn: "Oct 2021 - May 2024",
        highlights: [
            "Diseño, desarrollo y mantenimiento de APIs Java y microservicios Spring en AWS para soluciones bancarias.",
            "Gestión de ambientes de desarrollo, calidad, producción y homologación para canales móviles y web.",
            "Análisis y mantenimiento de infraestructura on-premise y cloud para liberar mejoras continuas.",
            "Diagnóstico, estimación, soporte y gestión de incidencias y fallos en producción.",
            "Gestión de entregables, integración de diseños técnicos, revisión de código y buenas prácticas de seguridad.",
            "Manejo de equipos, identificación de necesidades y uso de JIRA, Confluence y Bitbucket.",
            "Documentación de procesos, mentalidad ágil y metodologías Waterfall, Scrum, Kanban y SAFe.",
        ],
        workModeEn: "Remote",
        summaryEn:
            "Tech lead of a development team, owning technical definitions for web and mobile digital banking projects.",
        highlightsEn: [
            "Designed, built and maintained Java APIs and Spring microservices on AWS for banking solutions.",
            "Managed development, QA, production and homologation environments for mobile and web channels.",
            "Analyzed and maintained on-premise and cloud infrastructure to release continuous improvements.",
            "Handled diagnosis, estimation, support and production incident/failure management.",
            "Owned deliverables, technical design integration, code reviews and security best practices.",
            "Led teams, identified needs and used JIRA, Confluence and Bitbucket for delivery.",
            "Documented processes with an agile mindset across Waterfall, Scrum, Kanban and SAFe.",
        ],
        tech: ["Java", "Spring", "AWS", "Microservicios", "JIRA", "Confluence", "Bitbucket", "Scrum", "SAFe"],
    },
    {
        id: 3,
        title: "Senior Full Stack Java Developer",
        company: "iuvity",
        location: "Quito, Ecuador",
        period: "Mar 2017 - Dic 2021",
        workMode: "Presencial",
        logo: "/experience-logos/iuvity-icon.png",
        logoAlt: "iuvity logo",
        logoVariant: "icon",
        logoFit: "contain",
        summary:
            "Desarrollo de nuevas funcionalidades para el canal web SVP (Sucursal Virtual Personas) de Bancolombia y productos satélite del banco.",
        periodEn: "Mar 2017 - Dec 2021",
        highlights: [
            "Diseño, desarrollo y mantenimiento de APIs Java para soluciones bancarias de misión crítica.",
            "Estimación y pruebas de componentes de software con Java y Oracle en entornos de alto tráfico.",
            "Resolución de problemas técnicos críticos y colaboración multifuncional en disponibilidad y rendimiento.",
            "Aplicación de principios SOLID y patrones de diseño para features solicitadas por clientes.",
            "Code reviews y cumplimiento de estándares de codificación de la empresa.",
            "Stack backend Java (JEE/J2EE), Oracle y PL/SQL; frontend Spring MVC, JSP, Struts, jQuery, AngularJS.",
        ],
        workModeEn: "On-site",
        summaryEn:
            "Built new features for Bancolombia's SVP (Sucursal Virtual Personas) web channel and satellite banking products.",
        highlightsEn: [
            "Designed, developed and maintained Java APIs for mission-critical banking solutions.",
            "Estimated and tested software components with Java and Oracle in high-traffic environments.",
            "Resolved critical technical issues and collaborated cross-functionally on availability and performance.",
            "Applied SOLID principles and design patterns for client-requested features.",
            "Performed code reviews and enforced company coding standards.",
            "Backend stack: Java (JEE/J2EE), Oracle and PL/SQL; frontend: Spring MVC, JSP, Struts, jQuery, AngularJS.",
        ],
        tech: [
            "Java JEE",
            "Oracle",
            "PL/SQL",
            "Spring MVC",
            "Struts",
            "AngularJS",
            "jQuery",
            "Maven",
            "JUnit",
            "REST",
        ],
    },
    {
        id: 4,
        title: "Expert Development",
        company: "Servicio de Rentas Internas",
        location: "Ecuador",
        period: "Mar 2015 - Feb 2017",
        workMode: "Presencial",
        logo: "/experience-logos/sri-mark.svg",
        logoAlt: "Servicio de Rentas Internas logo",
        logoVariant: "icon",
        logoFit: "contain",
        summary:
            "Desde el área de proyectos, desarrollo de nuevos formularios y anexos para una correcta gestión tributaria en plataformas Java y Oracle.",
        companyEn: "Internal Revenue Service of Ecuador",
        periodEn: "Mar 2015 - Feb 2017",
        highlights: [
            "Construcción de formularios y anexos orientados a procesos tributarios y administrativos de usuarios finales.",
            "Desarrollo de aplicaciones Java y Oracle con foco en código limpio y funcional para producción.",
            "Integración de componentes empresariales con Alfresco, JBoss y persistencia PL/SQL.",
            "Trabajo con stack JSF, Struts, JSP, Hibernate, Maven, JUnit, REST y HTML.",
        ],
        workModeEn: "On-site",
        summaryEn:
            "From the projects area, built new forms and annexes for proper tax management on Java and Oracle platforms.",
        highlightsEn: [
            "Built forms and annexes for tax and administrative processes aimed at end users.",
            "Developed Java and Oracle applications with clean, production-ready code.",
            "Integrated enterprise components with Alfresco, JBoss and PL/SQL persistence.",
            "Worked with JSF, Struts, JSP, Hibernate, Maven, JUnit, REST and HTML.",
        ],
        tech: ["Java", "Spring Boot", "JSF", "Struts", "JSP", "Hibernate", "Maven", "JUnit", "REST", "Alfresco", "JBoss", "PL/SQL"],
    },
    {
        id: 5,
        title: "Technical Specialist",
        company: "Cobiscorp",
        location: "Ecuador",
        period: "Sep 2014 - Feb 2015",
        workMode: "Presencial",
        logo: "/experience-logos/cobis-icon.png",
        logoAlt: "Cobiscorp logo",
        logoVariant: "icon",
        logoFit: "contain",
        summary:
            "Especialista técnico en Java para soporte, gestión de defectos e incidencias, y evolución del Banking Core COBIS.",
        periodEn: "Sep 2014 - Feb 2015",
        highlights: [
            "Soporte y gestión de defectos e incidencias sobre el core bancario.",
            "Mantenimiento y desarrollo de nuevas funcionalidades del Banking Core.",
            "Trabajo con Java, servicios RESTful, JavaScript y Git sobre SQL Server 2008 y Sybase 15.",
        ],
        workModeEn: "On-site",
        summaryEn:
            "Java technical specialist for defect/incident management and evolution of the COBIS Banking Core.",
        highlightsEn: [
            "Provided support and managed defects and incidents on the banking core.",
            "Maintained and developed new Banking Core features.",
            "Worked with Java, RESTful services, JavaScript and Git on SQL Server 2008 and Sybase 15.",
        ],
        tech: ["Java", "RESTful", "JavaScript", "Git", "SQL Server 2008", "Sybase 15"],
    },
    {
        id: 6,
        title: "Developer Engineer II",
        company: "Cobiscorp",
        location: "Quito, Ecuador",
        period: "Ene 2012 - Sep 2014",
        workMode: "Presencial",
        logo: "/experience-logos/cobis-icon.png",
        logoAlt: "Cobiscorp logo",
        logoVariant: "icon",
        logoFit: "contain",
        summary:
            "Analista programador senior en Java, .NET y SQL/Sybase para el core bancario COBIS y el sistema CEN (Cobis Explorer .NET) en bancos de la región.",
        periodEn: "Jan 2012 - Sep 2014",
        highlights: [
            "Mantenimiento y nuevas funcionalidades del sistema CEN para bancos como Davivienda (Costa Rica) y Banco de Capital (Panamá).",
            "Desarrollo Cobis V con HTML5, CSS3, JavaScript, AngularJS, Kendo UI y Bootstrap.",
            "Desarrollo .NET con Visual Studio 2010, C#, VB 6.0, ASP.NET MVC 4, Telerik RadControls e Infragistics.",
            "Lógica de negocio y tuning en SQL Server 2008 y Sybase 15; Hyperion SQR 8.3.1.",
            "Stack Java empresarial: Eclipse, JEE, JPA, JTA, EJB, RESTful, Maven, TortoiseSVN y FindBugs.",
            "Metodologías Waterfall y ágiles (Scrum, Kanban y SAFe).",
        ],
        workModeEn: "On-site",
        summaryEn:
            "Senior analyst-programmer in Java, .NET and SQL/Sybase for the COBIS banking core and CEN (Cobis Explorer .NET) across regional banks.",
        highlightsEn: [
            "Maintained and extended CEN for banks such as Davivienda (Costa Rica) and Banco de Capital (Panama).",
            "Built Cobis V features with HTML5, CSS3, JavaScript, AngularJS, Kendo UI and Bootstrap.",
            "Delivered .NET work with Visual Studio 2010, C#, VB 6.0, ASP.NET MVC 4, Telerik RadControls and Infragistics.",
            "Implemented business logic and tuning on SQL Server 2008 and Sybase 15; Hyperion SQR 8.3.1.",
            "Enterprise Java stack: Eclipse, JEE, JPA, JTA, EJB, RESTful, Maven, TortoiseSVN and FindBugs.",
            "Worked under Waterfall and agile frameworks (Scrum, Kanban and SAFe).",
        ],
        tech: [
            "Java",
            "JEE",
            "JPA",
            "EJB",
            "ASP.NET",
            "C#",
            "AngularJS",
            "Kendo UI",
            "SQL Server",
            "Sybase",
            "Maven",
        ],
    },
    {
        id: 7,
        title: "Software Developer",
        company: "Vteksoftfin",
        location: "Quito, Ecuador",
        period: "Ago 2011 - Dic 2011",
        workMode: "Presencial",
        logo: "/experience-logos/vteksoftfin.svg",
        logoAlt: "Vteksoftfin logo",
        logoVariant: "icon",
        logoFit: "contain",
        summary:
            "Investigación, soporte, programación, mantenimiento y documentación de sistemas bancarios CRONOS-COOP para cooperativas de crédito.",
        periodEn: "Aug 2011 - Dec 2011",
        highlights: [
            "Desarrollo de nuevas funcionalidades del sistema CRONOS-COOP en Visual Studio .NET (2003–2008) con C#, VB.NET, VB 6 y SQL Server 2000–2008.",
            "Ajuste y tuning de rendimiento sobre SQL Server 2008.",
            "Desarrollo web con Telerik RadControls ASP.NET AJAX, JavaScript, ADO.NET, Entity Framework y servicios ASMX/WCF.",
            "Arquitectura estratificada con CSS, XML y buenas prácticas de mantenimiento.",
        ],
        workModeEn: "On-site",
        summaryEn:
            "Research, support, programming, maintenance and documentation of CRONOS-COOP banking systems for credit unions.",
        highlightsEn: [
            "Built new CRONOS-COOP features on Visual Studio .NET (2003–2008) with C#, VB.NET, VB 6 and SQL Server 2000–2008.",
            "Tuned and adjusted performance on SQL Server 2008.",
            "Delivered web work with Telerik RadControls ASP.NET AJAX, JavaScript, ADO.NET, Entity Framework and ASMX/WCF services.",
            "Applied layered architecture with CSS, XML and maintainable practices.",
        ],
        tech: ["C#", "VB.NET", "ASP.NET", "SQL Server", "Telerik", "ADO.NET", "Entity Framework", "WCF"],
    },
    {
        id: 8,
        title: "Docente de Computación",
        company: "Colegio Nacional Mixto Vilcabamba",
        location: "Vilcabamba, Loja, Ecuador",
        period: "2008 - 2011",
        workMode: "Presencial",
        logo: "/experience-logos/colegio-vilcabamba.png",
        logoAlt: "Colegio de Bachillerato Vilcabamba logo",
        logoVariant: "icon",
        logoFit: "cover",
        summary:
            "Docente de la materia de Computación: ofimática avanzada, alfabetización digital y proyectos prácticos con estudiantes de secundaria.",
        titleEn: "Computer Science Teacher",
        companyEn: "Colegio Nacional Mixto Vilcabamba",
        periodEn: "2008 - 2011",
        highlights: [
            "Impartí Word avanzado: estilos, tablas, índices, combinación de correspondencia y documentos académicos listos para entrega.",
            "Enseñé Excel con fórmulas, tablas dinámicas, gráficos y plantillas para presupuestos y registros escolares.",
            "Guié PowerPoint avanzado: storytelling visual, animaciones útiles y presentaciones orales con criterio de diseño.",
            "Introduje tipografía al tacto, organización de archivos, correo electrónico seguro y navegación responsable en internet.",
            "Practiqué armado básico de PC, instalación de software, antivirus y mantenimiento preventivo del laboratorio.",
            "Coordiné proyectos de fin de año: boletines digitales del curso, hojas de cálculo colaborativas y mini-ferias de tecnología.",
        ],
        workModeEn: "On-site",
        summaryEn:
            "Computer Science teacher covering advanced office tools, digital literacy and hands-on projects with high-school students.",
        highlightsEn: [
            "Taught advanced Word: styles, tables, indexes, mail merge and submission-ready academic documents.",
            "Taught Excel with formulas, pivot tables, charts and templates for budgets and school records.",
            "Guided advanced PowerPoint: visual storytelling, purposeful animations and oral presentations with design sense.",
            "Introduced touch typing, file organization, safe email use and responsible internet navigation.",
            "Practiced basic PC assembly, software install, antivirus and preventive lab maintenance.",
            "Coordinated year-end projects: class digital newsletters, collaborative spreadsheets and mini tech fairs.",
        ],
        tech: ["Word", "Excel", "PowerPoint", "Windows", "Internet", "Hardware básico"],
    },
    {
        id: 9,
        title: "Técnico de Sistemas Operativos",
        company: "SisproCompu",
        location: "Loja, Ecuador",
        period: "Oct 2007 - May 2008",
        workMode: "Presencial",
        logo: "/experience-logos/sisprocompu.png",
        logoAlt: "SisproCompu logo",
        logoVariant: "icon",
        logoFit: "contain",
        summary:
            "Técnico en configuración de servidores Windows y Linux, e informática de hardware y software.",
        titleEn: "Operating Systems Technician",
        periodEn: "Oct 2007 - May 2008",
        highlights: [
            "Instalación, configuración y mantenimiento de programas, antivirus y software ofimático.",
            "Soporte técnico de hardware y software en entorno empresarial.",
            "Configuración y administración básica de servidores Windows y Linux.",
        ],
        workModeEn: "On-site",
        summaryEn:
            "Technician for Windows and Linux server configuration, plus hardware and software IT support.",
        highlightsEn: [
            "Installed, configured and maintained applications, antivirus and office software.",
            "Provided hardware and software technical support in a business environment.",
            "Configured and performed basic administration of Windows and Linux servers.",
        ],
        tech: ["Windows Server", "Linux", "Hardware", "Software Support"],
    },
];

const logo = {
    certiprof: { logo: "/certification-logos/certiprof.png", logoAlt: "CertiProf logo" },
    platzi: { logo: "/certification-logos/platzi.svg", logoAlt: "Platzi logo" },
    linkedin: { logo: "/certification-logos/linkedin.svg", logoAlt: "LinkedIn logo" },
    efset: { logo: "/certification-logos/efset.png", logoAlt: "EF SET logo" },
    testdome: { logo: "/certification-logos/testdome.svg", logoAlt: "TestDome logo" },
    udemy: { logo: "/certification-logos/udemy.svg", logoAlt: "Udemy logo" },
    pluralsight: { logo: "/certification-logos/pluralsight.svg", logoAlt: "Pluralsight logo" },
    scrumAlliance: { logo: "/certification-logos/scrum-alliance.svg", logoAlt: "Scrum Alliance logo" },
    oracle: { logo: "/certification-logos/oracle.svg", logoAlt: "Oracle logo" },
    epn: { logo: "/certification-logos/epn.png", logoAlt: "EPN logo" },
} as const;

// Licencias y certificaciones (LinkedIn / PDF)
export const certifications = [
    {
        id: 1,
        name: "Curso de Programación Funcional con Java SE",
        nameEn: "Functional Programming with Java SE",
        field: "Java / Backend",
        fieldEn: "Java / Backend",
        issuer: "Platzi",
        period: "Feb 2026",
        periodEn: "Feb 2026",
        ...logo.platzi,
    },
    {
        id: 2,
        name: "EF SET English Certificate 60/100 (B2 Upper Intermediate)",
        nameEn: "EF SET English Certificate 60/100 (B2 Upper Intermediate)",
        field: "Idiomas",
        fieldEn: "Languages",
        issuer: "EF SET",
        period: "Ene 2026",
        periodEn: "Jan 2026",
        ...logo.efset,
    },
    {
        id: 3,
        name: "Curso de Python",
        nameEn: "Python Course",
        field: "Lenguajes",
        fieldEn: "Languages",
        issuer: "Platzi",
        period: "Ene 2026",
        periodEn: "Jan 2026",
        ...logo.platzi,
    },
    {
        id: 4,
        name: "Curso de Fundamentos de Arquitectura de Software",
        nameEn: "Software Architecture Fundamentals",
        field: "Arquitectura",
        fieldEn: "Architecture",
        issuer: "Platzi",
        period: "Dic 2025",
        periodEn: "Dec 2025",
        ...logo.platzi,
    },
    {
        id: 5,
        name: "Curso de React Avanzado",
        nameEn: "Advanced React",
        field: "Frontend",
        fieldEn: "Frontend",
        issuer: "Platzi",
        period: "Dic 2025",
        periodEn: "Dec 2025",
        ...logo.platzi,
    },
    {
        id: 6,
        name: "Curso de Inglés para el Uso de Inteligencia Artificial",
        nameEn: "English for Artificial Intelligence",
        field: "Idiomas / IA",
        fieldEn: "Languages / AI",
        issuer: "Platzi",
        period: "Dic 2025",
        periodEn: "Dec 2025",
        ...logo.platzi,
    },
    {
        id: 7,
        name: "Azure AZ-900 Prep. Cert.: Microsoft Azure Fundamentals",
        nameEn: "Azure AZ-900 Prep. Cert.: Microsoft Azure Fundamentals",
        field: "Cloud / Azure",
        fieldEn: "Cloud / Azure",
        issuer: "LinkedIn",
        period: "Mar 2025",
        periodEn: "Mar 2025",
        ...logo.linkedin,
    },
    {
        id: 8,
        name: "React",
        nameEn: "React",
        field: "Frontend / Evaluación",
        fieldEn: "Frontend / Assessment",
        issuer: "TestDome",
        period: "Ene 2024",
        periodEn: "Jan 2024",
        ...logo.testdome,
    },
    {
        id: 9,
        name: "Java",
        nameEn: "Java",
        field: "Backend / Evaluación",
        fieldEn: "Backend / Assessment",
        issuer: "TestDome",
        period: "Ene 2024",
        periodEn: "Jan 2024",
        ...logo.testdome,
    },
    {
        id: 10,
        name: "Java Spring Boot",
        nameEn: "Java Spring Boot",
        field: "Backend / Evaluación",
        fieldEn: "Backend / Assessment",
        issuer: "TestDome",
        period: "Ene 2024",
        periodEn: "Jan 2024",
        ...logo.testdome,
    },
    {
        id: 11,
        name: "Curso de Inglés para Programadores",
        nameEn: "English for Developers",
        field: "Idiomas",
        fieldEn: "Languages",
        issuer: "Platzi",
        period: "Nov 2023",
        periodEn: "Nov 2023",
        ...logo.platzi,
    },
    {
        id: 12,
        name: "Cómo crear un entorno de trabajo positivo y saludable",
        nameEn: "How to Create a Positive and Healthy Work Environment",
        field: "Liderazgo",
        fieldEn: "Leadership",
        issuer: "LinkedIn",
        period: "Nov 2023",
        periodEn: "Nov 2023",
        ...logo.linkedin,
    },
    {
        id: 13,
        name: "Habilidades de coaching para líderes y gerentes",
        nameEn: "Coaching Skills for Leaders and Managers",
        field: "Liderazgo / Coaching",
        fieldEn: "Leadership / Coaching",
        issuer: "LinkedIn",
        period: "Nov 2023",
        periodEn: "Nov 2023",
        ...logo.linkedin,
    },
    {
        id: 14,
        name: "Introducción a AWS: Seguridad",
        nameEn: "Introduction to AWS: Security",
        field: "Cloud / AWS",
        fieldEn: "Cloud / AWS",
        issuer: "LinkedIn",
        period: "Nov 2023",
        periodEn: "Nov 2023",
        ...logo.linkedin,
    },
    {
        id: 15,
        name: "Introducción a AWS: Servicios principales",
        nameEn: "Introduction to AWS: Core Services",
        field: "Cloud / AWS",
        fieldEn: "Cloud / AWS",
        issuer: "LinkedIn",
        period: "Nov 2023",
        periodEn: "Nov 2023",
        ...logo.linkedin,
    },
    {
        id: 16,
        name: "Lenguaje no verbal para líderes",
        nameEn: "Nonverbal Communication for Leaders",
        field: "Liderazgo / Comunicación",
        fieldEn: "Leadership / Communication",
        issuer: "LinkedIn",
        period: "Sep 2023",
        periodEn: "Sep 2023",
        ...logo.linkedin,
    },
    {
        id: 17,
        name: "Survey Contributor — The Agile Adoption Report 2021",
        nameEn: "Survey Contributor — The Agile Adoption Report 2021",
        field: "Agile",
        fieldEn: "Agile",
        issuer: "CertiProf",
        period: "May 2021",
        periodEn: "May 2021",
        ...logo.certiprof,
    },
    {
        id: 18,
        name: "Aprende Docker desde Cero a Swarm y Kubernetes",
        nameEn: "Docker from Zero to Swarm and Kubernetes",
        field: "DevOps / Contenedores",
        fieldEn: "DevOps / Containers",
        issuer: "Udemy",
        period: "May 2021",
        periodEn: "May 2021",
        ...logo.udemy,
    },
    {
        id: 19,
        name: "Leading through Crisis: Executive Briefing",
        nameEn: "Leading through Crisis: Executive Briefing",
        field: "Liderazgo",
        fieldEn: "Leadership",
        issuer: "Pluralsight",
        period: "Abr 2021",
        periodEn: "Apr 2021",
        ...logo.pluralsight,
    },
    {
        id: 20,
        name: "Big Data Professional Certificate",
        nameEn: "Big Data Professional Certificate",
        field: "Big Data",
        fieldEn: "Big Data",
        issuer: "CertiProf",
        period: "Abr 2021 · Exp. May 2023",
        periodEn: "Apr 2021 · Exp. May 2023",
        ...logo.certiprof,
    },
    {
        id: 21,
        name: "DevOps Essentials Professional Certificate — DEPC®",
        nameEn: "DevOps Essentials Professional Certificate — DEPC®",
        field: "DevOps",
        fieldEn: "DevOps",
        issuer: "CertiProf",
        period: "Abr 2021 · Exp. Abr 2023",
        periodEn: "Apr 2021 · Exp. Apr 2023",
        ...logo.certiprof,
    },
    {
        id: 22,
        name: "Cyber Security Foundation Professional Certificate — CSFPC™",
        nameEn: "Cyber Security Foundation Professional Certificate — CSFPC™",
        field: "Seguridad",
        fieldEn: "Security",
        issuer: "CertiProf",
        period: "Abr 2021 · Exp. Abr 2023",
        periodEn: "Apr 2021 · Exp. Apr 2023",
        ...logo.certiprof,
    },
    {
        id: 23,
        name: "Remote Work and Virtual Collaboration Professional Certificate — RWVCPC",
        nameEn: "Remote Work and Virtual Collaboration Professional Certificate — RWVCPC",
        field: "Trabajo remoto",
        fieldEn: "Remote work",
        issuer: "CertiProf",
        period: "Abr 2021 · Exp. Abr 2023",
        periodEn: "Apr 2021 · Exp. Apr 2023",
        ...logo.certiprof,
    },
    {
        id: 24,
        name: "How to develop emotional intelligence",
        nameEn: "How to develop emotional intelligence",
        field: "Liderazgo / Soft skills",
        fieldEn: "Leadership / Soft skills",
        issuer: "LinkedIn",
        period: "Abr 2021",
        periodEn: "Apr 2021",
        ...logo.linkedin,
    },
    {
        id: 25,
        name: "Scrum Developer Professional Certificate",
        nameEn: "Scrum Developer Professional Certificate",
        field: "Agile / Desarrollo",
        fieldEn: "Agile / Development",
        issuer: "CertiProf",
        period: "Abr 2021 · Exp. Abr 2023",
        periodEn: "Apr 2021 · Exp. Apr 2023",
        ...logo.certiprof,
    },
    {
        id: 26,
        name: "Scrum Product Owner Professional Certificate",
        nameEn: "Scrum Product Owner Professional Certificate",
        field: "Agile / Producto",
        fieldEn: "Agile / Product",
        issuer: "CertiProf",
        period: "Abr 2021 · Exp. Abr 2023",
        periodEn: "Apr 2021 · Exp. Apr 2023",
        ...logo.certiprof,
    },
    {
        id: 27,
        name: "Scrum Master Professional Certificate — SMPC®",
        nameEn: "Scrum Master Professional Certificate — SMPC®",
        field: "Agile / Scrum",
        fieldEn: "Agile / Scrum",
        issuer: "CertiProf",
        period: "Abr 2021 · Exp. Abr 2023",
        periodEn: "Apr 2021 · Exp. Apr 2023",
        ...logo.certiprof,
    },
    {
        id: 28,
        name: "Lifelong Learning",
        nameEn: "Lifelong Learning",
        field: "Desarrollo profesional",
        fieldEn: "Professional development",
        issuer: "CertiProf",
        period: "Abr 2021",
        periodEn: "Apr 2021",
        ...logo.certiprof,
    },
    {
        id: 29,
        name: "Scrum Foundation Professional Certificate",
        nameEn: "Scrum Foundation Professional Certificate",
        field: "Agile / Fundamentos",
        fieldEn: "Agile / Foundations",
        issuer: "CertiProf",
        period: "Abr 2021 · Exp. Abr 2023",
        periodEn: "Apr 2021 · Exp. Apr 2023",
        ...logo.certiprof,
    },
    {
        id: 30,
        name: "Emotional intelligence",
        nameEn: "Emotional intelligence",
        field: "Liderazgo / Soft skills",
        fieldEn: "Leadership / Soft skills",
        issuer: "Platzi",
        period: "Abr 2020",
        periodEn: "Apr 2020",
        ...logo.platzi,
    },
    {
        id: 31,
        name: "Competencia en inglés",
        nameEn: "Proficiency in English",
        field: "Idiomas",
        fieldEn: "Languages",
        issuer: "CEC — Escuela Politécnica Nacional",
        period: "May 2015",
        periodEn: "May 2015",
        ...logo.epn,
    },
    {
        id: 32,
        name: "Certified ScrumMaster (CSM)",
        nameEn: "Certified ScrumMaster (CSM)",
        field: "Agile / Scrum",
        fieldEn: "Agile / Scrum",
        issuer: "Scrum Alliance",
        period: "Dic 2014",
        periodEn: "Dec 2014",
        ...logo.scrumAlliance,
    },
    {
        id: 33,
        name: "Oracle Certified Professional, Java SE 6 Programmer",
        nameEn: "Oracle Certified Professional, Java SE 6 Programmer",
        field: "Java / Backend",
        fieldEn: "Java / Backend",
        issuer: "Oracle",
        period: "Feb 2013",
        periodEn: "Feb 2013",
        ...logo.oracle,
    },
];

// Educación
export const education = [
    {
        id: 1,
        degree: "Maestría en Gerencia de Sistemas",
        degreeEn: "Master's in Systems Management",
        field: "Ciencias Informáticas",
        fieldEn: "Computer Science",
        school: "Universidad de las Fuerzas Armadas — ESPE",
        period: "2015 – 2017",
        logo: "/education-logos/espe.png",
        logoAlt: "ESPE logo",
        logoVariant: "icon" as const,
        logoFit: "contain" as const,
    },
    {
        id: 2,
        degree: "Ingeniería en Sistemas",
        degreeEn: "Systems Engineering",
        field: "Ciencias de la Computación",
        fieldEn: "Computer Science",
        school: "Universidad Nacional de Loja",
        period: "2002 – 2008",
        logo: "/education-logos/unl-icon.png",
        logoAlt: "Universidad Nacional de Loja logo",
        logoVariant: "icon" as const,
        logoFit: "cover" as const,
    },
];

// Reconocimientos
export const awards = [
    { id: 1, name: "1er lugar — Advanced Programming in Java", issuer: "Competencia de programación" },
    { id: 2, name: "2do lugar — Advanced Programming in Java", issuer: "Competencia de programación" },
];

// Idiomas
export const languagesData = [
    { id: 1, name: "Español", level: "Nativo", percent: 100 },
    { id: 2, name: "Inglés", level: "Profesional (working)", percent: 75 },
];
